# Generated by Django 4.1.7 on 2023-05-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='info',
            field=models.TextField(blank=True),
        ),
    ]
