# Generated by Django 4.1.7 on 2023-05-18 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_courses_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='category',
            field=models.CharField(choices=[('Programming', 'Программирование'), ('Design', 'Дизайн'), ('Construction', 'Строительство')], max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='status',
            field=models.CharField(choices=[('Published', 'Опубликованно'), ('Moderate', 'На модерации'), ('Withdrawn', 'Снято с публикации')], max_length=255),
        ),
    ]
