# Generated by Django 4.1.7 on 2023-05-18 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_courses_category_alter_courses_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='institution',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.institutions'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='priority',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='courses',
            name='status',
            field=models.CharField(blank=True, choices=[('Published', 'Опубликованно'), ('Moderate', 'На модерации'), ('Withdrawn', 'Снято с публикации')], max_length=255),
        ),
    ]
